[package]
name = "lmu-steward-companion"
version = "0.1.2"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "lmu_steward_companion_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
steamlocate = "2.0.1"
reqwest = { version = "0.12", features = ["json"] }
tokio = { version = "1", features = ["full"] }
thiserror = "1.0"
quick-xml = { version = "0.37.5", features = ["serialize", "serde"] }
serde_derive = "1.0.219"
chrono = "0.4.41"
regex = "1.10.3"
rust_xlsxwriter = "0.87.0"
tauri-plugin-dialog = "2"
oauth2 = { version = "4.4", features = ["reqwest"] }
tokio-util = "0.7"
url = "2.5"
